language: node_js
node_js:
  - "node"
warnings_are_errors: false
script:
  - echo '*** Starting build ***' 
  - echo 'install dependencies'
  - cd client && npm install
  - npm i node-sass@4.14 
  - npm i --save-dev cross-env
  - echo 'Running Build'
  - npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $firebase_token
  on:
    branch: client