language: node_js
node_js:
  - 14
script:
  - echo '*** Starting build ***'
  - echo 'install dependencies'
  - cd api && npm install
  - echo 'Running test'
  - cd api && npm run test
deploy:
  provider: heroku
  api_key: $heroku_key
  app: $heroku_app_name
  on:
    branch: api_master