export * as categoryAPI from './categoryApi'
export * as userAPI from './userApi'
export * as productAPI from './prodcutApi'
export * as watchListApi from './watchListApi'
export * as bidderApi from './bidderApi'
export * as ratingApi from './ratingApi'
