language: node_js
node_js:
  - 14
script:
  - echo '*** Starting build ***'
  - echo 'install dependencies'
  - npm install
  - echo 'Running test'
  - npm run test
deploy:
  provider: heroku
  api_key: $heroku_key
  app: $heroku_app_name